### PR TITLE
fix(android): use ViewCompat.setStateDescription for API < 30 compat

### PR DESCRIPTION
**Pull request by Mohamed-kassim**
## Problem

`TrueSheetGrabberView.updateAccessibilityValue()` calls `View.stateDescription` directly, which was added in **API 30 (Android 11)**. On Android 10 and below, this causes a fatal `NoSuchMethodError` crash on every sheet present:

```
NoSuchMethodError: No virtual method setStateDescription(Ljava/lang/CharSequence;)V
in class Lcom/lodev09/truesheet/core/TrueSheetGrabberView;
```

Introduced in #587 (v3.10.0-beta.0), still present in v3.10.0-beta.2.

## Fix

Replace the direct `stateDescription = ...` assignment with `ViewCompat.setStateDescription(this, description)`, which handles the API check internally (no-op on API < 30, delegates to the platform method on API 30+).

## Impact

In our production app (Tarteel, ~1M users), this caused **100+ affected users and 389+ crash events within 1 hours** of shipping a release with v3.10.0-beta.1.

### CODE REVIEW

**Review by lodev09 — APPROVED** [review]
Thanks!

**Comment by lodev09** [comment]
:rocket: _This pull request is included in v3.10.0. See [Release 3.10.0](https://github.com/lodev09/react-native-true-sheet/releases/tag/v3.10.0) for release notes._
